[package]
name = "light-kafka-exporter"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prometheus_exporter = "0.8.2"
prometheus = { version =  "0.13.0", features = ["process"] }
rdkafka = "0.26.0"
clap = "3.0.0-beta.4"
anyhow = "1.0.44"
humantime = "2.1.0"
chrono = "0.4.19"
